### ISSUE TITLE
Error: cannot find module ../../package.json after update ncu to 12.0.1

### ISSUE THREAD

**Issue by Boul3ez85** [raineorshine/npm-check-updates#991] opened 2021-11-09 01:58 UTC
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

After updating ncu to version 12.0.1, use this command:
```
npm i -g npm-check-updates
```
I had the following issue:
```
Error: Cannot find module '../../package.json'
Require stack:
- /usr/lib/node_modules/npm-check-updates/build/src/bin/cli.js
```
it works fine before this update, can someone help me please to remedy this issue?

**Comment by jcurlier** [comment] 2021-11-09 02:05
+1

**Comment by SwedishBarbarossa** [comment] 2021-11-09 04:34
Not a solution, but I had the same problem and just installed the previous version:
`sudo npm install npm-check-updates@12.0.0 -g`
or
`npm install npm-check-updates@12.0.0`
if you have it installed locally. That version worked just fine.

**Comment by XhmikosR** [comment] 2021-11-09 05:36
Duplicate of #990

**Closed by XhmikosR** 2021-11-09 05:36 UTC

**Comment by Boul3ez85** [comment] 2021-11-09 06:01
it's fixed now, thank you guys!
just change from "../../package.json" to "../../../package.json" in the file '/usr/lib/node_modules/npm-check-updates/build/src/bin/cli.js' line 11

**Comment by raineorshine** [comment] 2021-11-09 14:37
Fixed and published in `v12.0.2`.

**Comment by raineorshine** [comment] 2021-11-09 14:38
> +1

@jcurlier I encourage you to use github's built-in reactions like 👍 rather than create a "+1" comment, which adds noise to the discussion and increases notifications for everyone.
