### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN issue with private registry

### ISSUE THREAD

**Issue by tirthaguha** [raineorshine/npm-check-updates#706] opened 2020-07-27 11:15 UTC
- [x ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ x] I am using the latest version of `npm-check-updates`
- [ x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
I'm trying to use a private npm registry, and of course the certificate on that is not a standard one. 
my npmrc file has strict-ssl=false
when I run `ncu ` it throws error 
`self signed certificate in certificate chain`
## Current Behavior
when I run `ncu ` it throws error 
`self signed certificate in certificate chain`
## Expected Behavior
not throw the error, or have options to suspend the error

**Comment by raineorshine** [comment] 2020-07-27 15:42
Please search existing issues. This is a duplicate of #636 and #694. There may be an issue with `pacote` passing `strict-ssl` through to `npm`. Thanks!

**Closed by raineorshine** 2020-07-27 15:42 UTC

**Comment by tirthaguha** [comment] 2020-07-28 05:10
Wow, you're rude, You're just passing the buck here. you should declare in your readme that this code has a limitation. We don't know when pacote is going to fix it, or are they going to fix it ever, which makes your code useless in the case of private npm registries.

**Comment by raineorshine** [comment] 2020-07-28 14:18
That's a good suggestion. I will do that.

**Comment by raineorshine** [comment] 2020-08-04 20:19
@tirthaguha Potential fix made in #713 and published in `v7.0.3-alpha.1`. Will you try it out and let me know if it fixes the problem for you?

**Comment by tirthaguha** [comment] 2020-08-05 12:05
@raineorshine it works, thanks. no errors and it was able to show the versions available in my private registry.
