### ISSUE TITLE
error: cannot find rimraf

### ISSUE THREAD

**Issue by its-dibo** [raineorshine/npm-check-updates#1376] opened 2024-03-12 13:17 UTC
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

Node.js v20.10.0

I just run `npx npm-check-updates`
```
but got this error

```
node:internal/modules/cjs/loader:598
      throw e;
      ^

Error: Cannot find module 'node_modules/rimraf/dist/commonjs/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1181:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1169:15)
    at resolveExports (node:internal/modules/cjs/loader:591:14)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (node_modules/npm-check-updates/build/src/lib/doctor.js:30:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'node_modules/rimraf/package.json'
}

Node.js v20.10.0
```

**Comment by its-dibo** [comment] 2024-03-12 13:26
related, but still not working
https://github.com/raineorshine/npm-check-updates/pull/1372

**Comment by raineorshine** [comment] 2024-03-12 13:28
Let's close this in favor of #1367. You can add a note there that it also affects node v20. 

Unfortunately, it seems to be specific to your machine or node build since I'm not able to reproduce it and others are not reporting the issue.

**Closed** 2024-03-12 13:30 UTC
Labels: duplicate
