### ISSUE TITLE
AbortController is not defined in v12.5.4

### ISSUE THREAD

**Issue by AminFazlMondo** [raineorshine/npm-check-updates#1073] opened 2022-03-24 21:53 UTC
- [ x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ x] I am using the latest version of `npm-check-updates`
- [ x] I am using `node >= 12`

---------------------------

## Steps to Reproduce
environment:

- NPM: 6.14.15
- node: 14.18.0
- npm-check-updates: 12.5.4

ran
```
npx npm-check-updates
```

## Current Behavior
The command fails with `AbortController is not defined`

## Expected Behavior
The command should list the dependencies to be updated

**Comment by raineorshine** [comment] 2022-03-24 22:06
Thanks for reporting. npm-check-updates hasn't changed recently, so it seems like this should still work. 

Does npm-check-updates work if you install it globally? Does npx work for you on other packages?

**Comment by AminFazlMondo** [comment] 2022-03-24 22:16
I beleive this is caused by a dependency, I thought it would be good to capture that here for everyone's benefit and also see if there is workaround.
And it fails on all my packages, I have downgraded to `12.5.3` and works fine.
I think the dependency chain with issue is 
```
hosted-git-info -> lru-cache
```

**Comment by raineorshine** [comment] 2022-03-25 12:41
Okay, good to know. If you haven't already, I recommend opening an issue in the offending project, and linking it here.

**Comment by bbeesley** [comment] 2022-04-01 12:55
> Okay, good to know. If you haven't already, I recommend opening an issue in the offending project, and linking it here.

The issue is fixed on the offending project, and fixed on the dependency that requires the offending project. Unfortunately this repo is pinned to the previous major release, so it isn't gonna take that fix automatically. I've opened a PR to bump that dependency which should get things working again. I use npm-check-updates on dozens of projects that are stuck on node 14, so I'm up to my eyes in failed updates right now, so hopefully this will the fastest way to get it working again.

**Comment by raineorshine** [comment] 2022-04-03 14:36
Published in `v12.5.5`

**Closed by raineorshine** 2022-04-03 14:36 UTC
Labels: dependency-bug
