### ISSUE TITLE
Incorrectly waits for stdin

### ISSUE THREAD

**Issue by Igloczek** [raineorshine/npm-check-updates#136] opened 2015-09-20 12:06 UTC
Looks like ncu is currently not compatible with Node v4.1.0. I can run ncu, but nothing happens - cursor just goes to new line.

**Comment by metaraine** [comment] 2015-09-21 15:43
I installed node v4.1.0 and ran `ncu` without a problem. All unit tests passing, too.

What happens when you run this command?

```
echo '{"dependencies":{"express": "1"}}' | ncu
```

Please provide any additional information you can about the problem.

**Comment by Igloczek** [comment] 2015-09-21 21:56
```
echo '{"dependencies":{"express": "1"}}' | ncu
express  1  →  4 
```
``ncu`` without any extra parameters works too, but it takes over 3 minutes to get results...

**Comment by MrHyde** [comment] 2015-09-22 06:11
Same here with node 4.1
Sometimes it takes even longer

```
Measure-Command {ncu}

Seconds           : 15
Milliseconds      : 392
Ticks             : 153923946
```

**Comment by metaraine** [comment] 2015-09-22 14:49
It looks like it's working. It may take a long time if your package.json is long since `npm view` has to be called for each dependency to get the latest version number. If you know of a way to get latest versions of multiple dependencies in one call, we could speed this up considerably, but [npm view](https://docs.npmjs.com/cli/view) does not appear to support it.

Another user experience improvement would be to buffer the results to stdout so that you could see dependencies as they were found, instead of waiting till the end. This would require a significant refactor.

Sorry I don't have a good answer. Let me know if you think of something that I haven't!

**Comment by MrHyde** [comment] 2015-09-22 23:46
I had pretty much the same issue last night, but it was apparently related to slow connection to npm registry. But as you said - it's not really intuitive at the moment and people can just stare there at blinking cursor and wondering that's going on. Is there any options for verbose output?

**Comment by metaraine** [comment] 2015-09-23 14:58
It would be simple enough to print “Finding latest versions from npm…” at
the start.

**Comment by mrhyde** [comment] 2015-09-23 15:33
Sounds good for me :)

**Comment by kalmanb** [comment] 2015-09-24 10:51
Note I had the same issue, was burning lot so CPU and not returning. Cleaned/removed node_modules directory fixed for me.

**Comment by metaraine** [comment] 2015-09-26 17:09
@kalmanb Thanks... I'm not sure what is happening there, but definitely is problematic. Let's keep an eye on it, and if we can reproduce it with a given install state then we can debug.

**Comment by etiktin** [comment] 2015-09-26 21:24
Refactoring so we can check each dependency and print it's state as we get it sounds good to me. It will also make it easier to support interactive mode (#95).
For this to work we will need to rethink how we display satisfied dependencies that are not on the latest (currently we display them in a different group after all the unsatisfied).

Mean while, we could use the [progress](https://www.npmjs.com/package/progress) module or something similar, that allows us to show a progress bar in the CLI. The 'total' will be the number of dependencies and as we retrieve the latest version for each one, we will increase it by one. For example:
```
Finding latest versions [====          ] 13.7s
```

**Comment by metaraine** [comment] 2015-09-26 23:31
Good points. We spent [a bit of timing discussing](https://github.com/tjunnone/npm-check-updates/issues/94) satisfied text, but it's probably worth changing in order to get incremental installs and interactive mode. Let's discuss in #95.

Progress bar would be good!

**Comment by Daniel15** [comment] 2015-10-11 20:32
> ncu without any extra parameters works too, but it takes over 3 minutes to get results...

Are you using npm v3? It had pretty bad performance problems until recently (see http://blog.npmjs.org/post/130359991775/npm-weekly-31-npm-3-speed-fixes-modules-demoed and https://github.com/npm/npm/releases/tag/v3.3.6) which could explain the slowness

**Comment by Igloczek** [comment] 2015-10-12 18:33
@Daniel15 Nope, npm v2.14.4 + node v4.1.1.

**Comment by metaraine** [comment] 2015-10-13 18:55
I'm tagging this `unable-to-reproduce` as aside from the performance issues mentioned above, which could give the appearance of nothing happening , I am unable to reproduce a concrete bug.

**Comment by mriehema** [comment] 2015-10-30 16:26
I'm using npm v2.14.4 and node v4.1.1 with Windows 7, 64bit and ncu is not working. It starts, but never quits. Without any logs I cant check why. Tried to use it with "time ncu", because it may take longer, but I aborted it after 2 hours waiting. My package.json just has 16 entries. Any idea?

**Comment by metaraine** [comment] 2015-11-01 23:33
Hi Michael, thanks for reporting. Clearly it is getting hung up somewhere. We should add verbose logs so that we could at least see where it is hanging. Until then, the best we could do is actually debug from the source code.

Does it hang on an empty package.json? `echo "{}" > package.json && ncu`
Does it hang for some of the dependencies but not others? You could test this by removing some dependencies from your package.json and running ncu, or removing all of them and then adding them back in one-by-one.

Adding console.log's or more robust logging is going to be the best approach to really find where in the code it hangs, but since I cannot reproduce you may be on your own for the time being. Perhaps someone else who can reproduce would be willing to debug.

**Comment by mriehema** [comment] 2015-11-05 12:43
> Does it hang on an empty package.json? echo "{}" > package.json && ncu
Yes.

I tried to debug and added some logging to `function programRunLocal()` before return:
	console.log(pkgFileName);
	console.log(pkgFile);
	console.log(pkgData);
Tested with an empty package.json returns:
    package.json
    undefined
    lib$rsvp$promise$$Promise {
      _id: 0,
      _label: undefined,
      _state: undefined,
      _result: undefined,
      _subscribers: [] }
And it never gets to analyzeProjectDependencies() and doesn't stop.

**Comment by metaraine** [comment] 2015-11-05 18:54
Great information, thank you Michael. Maybe readFileAsync is not resolving? Can you tell if pkgData (promise) is resolving? Maybe add `.catch` to pkgData at the end of `programRunLocal` and see if an error is getting swallowed. Or try `pkgData.then(console.log.bind(console, 'hi'))` without the partial functional application, just to test a simpler case.

I wish I was able to reproduce and troubleshoot directly...

**Comment by metaraine** [comment] 2015-11-10 15:57
@mriehema I added verbose logging to v2.40. Can you upgrade then report the output of the following command?

```
ncu --loglevel verbose
```

**Comment by mriehema** [comment] 2015-11-10 16:59
Awesome! I would upgradeand test it, if I could:

```
$ npm install npm-check-updates -g

> snyk@1.1.1 postinstall C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\snyk
> node cli/index.js help api-license

The use of Snyk's API, whether through the use of the 'snyk' npm package or otherwise, is subject to the terms & conditions specified here: https://snyk.io/policies/customer-agreement.pdf

C:\Users\mriehema\AppData\Roaming\npm\npm-check-updates -> C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates\bin\old-alias
C:\Users\mriehema\AppData\Roaming\npm\ncu -> C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates\bin\npm-check-updates

> npm-check-updates@2.4.0 postinstall C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates
> npm run snyk-protect


> npm-check-updates@2.4.0 snyk-protect C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates
> snyk protect

ENOENT: no such file or directory, open 'C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\bower\node_modules\handlebars\node_modules\uglify-js\.snyk-npm:uglify-js:20150824.flag'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mriehema\\AppData\\Roaming\\npm\\node_modules\\npm-check-updates\\node_modules\\npm\\bin\\npm-cli.js" "run" "snyk-protect"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! npm-check-updates@2.4.0 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-check-updates@2.4.0 snyk-protect script 'snyk protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the npm-check-updates package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     snyk protect
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-check-updates
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mriehema\AppData\Roaming\npm\node_modules\npm-check-updates\npm-debug.log
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm-check-updates" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! npm-check-updates@2.4.0 postinstall: `npm run snyk-protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-check-updates@2.4.0 postinstall script 'npm run snyk-protect'.
npm ERR! This is most likely a problem with the npm-check-updates package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run snyk-protect
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-check-updates
npm ERR! There is likely additional logging output above.
```

**Comment by metaraine** [comment] 2015-11-10 22:11
Snyk would be great if it worked out of the box, but it's not worth adding if it is going to break in some environments. I'll remove it.

**Comment by metaraine** [comment] 2015-11-10 22:17
Try it now :). v2.4.1

**Comment by robertbaker** [comment] 2015-11-11 00:51
@metaraine shouldn't synk be a dev-dep instead?

**Comment by mriehema** [comment] 2015-11-11 09:29
@metaraine Thanks for your support. So I checked it:

´´´
$ ncu --loglevel verbose
Initializing...
Running in local mode...
Finding local package file...
Waiting for package data on stdin...
´´´
BTW: I updated to node v4.2.2 and npm v2.14.7

**Comment by mriehema** [comment] 2015-11-11 10:03
Success! After some more debugging I tried to run it with explicit packageFile, and it works!
`ncu --loglevel verbose --packageFile package.json`

Looks like `pkgData = require('get-stdin-promise');` is not working as expected.

**Comment by etiktin** [comment] 2015-11-11 15:36
The question is why didn't it find the local package.json when you run it without parameters. "Finding local package file..." was supposed to succeed so it shouldn't have tried to read it from stdin.

By the way, we can replace `get-stdin-promise` with [`get-stdin`](https://www.npmjs.com/package/get-stdin) since they added builtin support for promises in v5.0.0.

**Comment by metaraine** [comment] 2015-11-11 17:46
@etiktin npm-check-updates waits for stdin if [`process.stdin.isTTY`](https://nodejs.org/api/process.html#process_process_stdout) is false. This is the proper way to check for stdin afaik, but please educate me if someone knows otherwise. npm-check-updates will look for a local package file only if it is not expecting anything from stdin. That message would probably be more accurate if it said "Finding package file data..."

@mriehema I wonder why isTTY is returning false when you are not piping anything to stdin. I googled "process.stdin.isTTY Windows" to see if it was something specific to your OS, but didn't turn up anything. Using --packageFile will work in the mean time. Thanks for your persistence!

@robertbaker snyk added itself to the package.json, so if anything is incorrect, it is due to snyk installing itself incorrectly, which for me is a good reason to hold off until they get that straightened out.

**Comment by mriehema** [comment] 2015-11-26 14:17
FYI: Updated to ncu v2.5.1 but it still doesn't work without `--packageFile`

```
$ ncu -l silly
Initializing...
Running in local mode...
Finding package file data...
Waiting for package data on stdin...
```

**Comment by metaraine** [comment] 2015-12-06 18:13
I'll keep this issue open since ncu still incorrectly waits for stdin in some environments. Adding an explicit `--packageFile` is a viable workaround.

As for the general performance issues, I fixed a bottleneck that should give a ~3x speed improvement (published in `v2.5.3`).

**Comment by mikemagnusw** [comment] 2015-12-07 14:19
Confirming hang on Windows 8.
Windows, being backwards, has no native concept of a TTY. I'm not going to dig into it myself as specifying the package file explicitly of course works, but unless any underlying package/implementation of `isTTY` is Cygwin-aware i wouldn't expect things to work out well.

**Comment by mriehema** [comment] 2015-12-08 09:57
@mikemagnusw Thx for this infos. 
Updated to v2.5.4 and used ncu in Git Bash. Still same error. Used in cmd.exe. Works.
Git Bash based on MinTTY. Found an issue according to  STDIN, see  https://github.com/mintty/mintty/issues/56

**Comment by etiktin** [comment] 2015-12-08 16:50
I can confirm it's happening with MinTTY (Cygwin/Babun). I tried it with node v4 and v0.12 and in both of them it's waiting for stdin.

This issue also happens when you try to run node with no parameters. In cmd it will enter node's REPL, but on MinTTY it will wait for stdin (you can force it to go to REPL by passing `-i`).

As a possible solution we could try to recognize we're running on Cygwin (e.g. check the env for the `CYGWIN` key, but there's probably a better way), and skip waiting for stdin. We can add a flag to force wait for stdin, for those rare cases when you want to pipe the data over.

**Comment by metaraine** [comment] 2015-12-08 16:54
@etiktin Just fyi, adding a flag to force wait for stdin is merely the inverse of requiring `--packageFile` to not wait.

npm-check-updates must not be the only module that looks for input on stdin by default. There are so many unix modules that do that.

**Comment by etiktin** [comment] 2015-12-08 17:39
There's an open issue about `process.stdout.isTTY` not working with MinTTY:
https://github.com/nodejs/node/issues/3006

> adding a flag to force wait for stdin is merely the inverse of requiring --packageFile to not wait.

I'm aware of that, but I think the inverse is more aligned with the way people actually use it (I assume most use ncu without params and expect it to read their package.json as opposed to piping the data).

**Comment by Daniel15** [comment] 2015-12-08 19:29
> I think the inverse is more aligned with the way people actually use it (I assume most use ncu without params and expect it to read their package.json as opposed to piping the data).

+1

I think a lot of apps take a hyphen as the file name in order to read from stdin. See http://unix.stackexchange.com/questions/41828/what-does-dash-at-the-end-of-a-command-mean for example.

**Comment by tw0517tw** [comment] 2016-02-15 16:12
for Git Bash users with MinTTY:
try `winpty ncu.cmd`
or add `alias ncu='winpty ncu.cmd'` to your `.bashrc`

**Comment by sant123** [comment] 2016-04-06 15:16
It works as the @tw0517tw way.

**Comment by raineorshine** [comment] 2017-02-12 14:04
Would someone who is on Windows and has to specify an explicit packageFile try out the following two commands and let me know the output?

1. `node -p process.stdin.constructor.name`
2. `echo "something" | node -p process.stdin.constructor.name`

Possible new insights from https://github.com/nodejs/node/issues/2339#issuecomment-279209070

**Comment by mriehema** [comment] 2017-02-12 15:31
In GitBash:
```
$ node -p process.stdin.constructor.name
ReadStream

$ echo "something" | node -p process.stdin.constructor.name
stdin is not a tty

$ node -v
v6.9.5

$ git --version
git version 2.11.1.windows.1
```

In Windows Console (cmd), which I don't use:

```
C:\Users\Michael>node -p process.stdin.constructor.name
ReadStream

C:\Users\Michael>echo "something" | node -p process.stdin.constructor.name
Socket
```

**Comment by davidgilbertson** [comment] 2017-02-17 21:33
I'm getting this problem too.

Windows 10, Git Bash, Node 7.1, ncu 2.10.2.

It works fine in `cmd`, and today is the first time I've ever had a problem after years of use.

`process.stdin.isTTY` returns true.

![image](https://cloud.githubusercontent.com/assets/4443482/23083944/38087094-f5b4-11e6-82d3-cba764acad02.png)

I get the same results as @mriehema in the comment above

P.S. awesome package
P.P.S. [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) @raineorshine if you want a Windows environment to test on

**Comment by raineorshine** [comment] 2017-02-17 22:57
@davidgilbertson Thanks! What happens when you try specifying a package file explicitly with `--packageFile package.json`?

**Comment by dscho** [comment] 2017-02-22 12:26
> echo "something" | node -p process.stdin.constructor.name

Please note that in Git Bash it makes a difference whether you call `node` or `node.exe`. The form without `.exe` assumes that you want to use node.js interactively, and fakes a Win32 Console (which Git Bash usually does not have, so you won't see any output if you call `node.exe` without any parameters and expect an interactive console).

**Comment by mackr2015** [comment] 2017-07-04 06:47
Hey guys, this command worked out for me.
Using gitbash MinTTY.
Try running this command
ncu -u --packageFile package.json
![npm-check-updates](https://user-images.githubusercontent.com/14350389/27818317-faa59b90-6049-11e7-8821-b00ec28707c6.png)

**Comment by ZWTOKIO** [comment] 2017-08-29 06:18
step 1 : ncu --loglevel verbose --packageFile package.json
step 2 :  ncu -u --packageFile package.json

**Comment by kylios** [comment] 2017-11-28 22:44
I've had a similar issue when using `ncu` within a docker container in gitlab CI. It relates to this issue with `process.stdin.isTTY`, but I suspect there may be an unrelated bug here, so let me know if I should file a separate issue for this.

I was confused when running `ncu -e 2` was correctly exiting with status code 1 from my shell, but in our CI pipeline it would consistently return status code 0, despite the package version table looking identical. I added many debugging statements and determined that the `options` object was identical in both cases: both environments had `options.cli` set to `true` and `options.errorLevel` set to `2`, so the `programError` function should have been exiting with an erroneous status code. However, I noticed that I wasn't getting the message `Dependencies not up-to-date` in my docker environment, while I was seeing that message in my shell. Tracing this in both environments, I found that `args.pkgFile` was `undefined` in docker, but it was set to `package.json` in my shell. Weird!

To make a long story short, I traced the issue down to the `findPackage` function, and the `process.stdin.isTTY` check, which was evaluating differently from my docker CI environment and my shell environment. In docker, `process.stdin.isTTY` is false, so this if-statement was being entered, but of course I wasn't supplying any data into stdin, so it was falling back and calling `pkgFile = findUp.sync(pkgFileName);` after the `isEmptyStdin` check. **This is where the bug is**: `pkgFile` is being returned as `undefined` from `findPackage`, despite `pkgFileName` being correct and `getPackageDataFromFile` reading the correct file and returning the right contents. My suspicion is that the value of `pkgFile` is not exiting the closure correctly, or else the promise returned from `findPackage` is resolving too soon. Regardless, the solution is what has already been stated here: simply invoke the script with the `--packageFile` argument and avoid the whole stdin thing.

I hope this helped somebody's debugging!

**Comment by raineorshine** [comment] 2019-03-16 04:05
@kylios I wanted to thank you for your debugging and detailed explanation of what you found. It helped me fix a related bug (4f6b4a380). My apologies for closing the issue with no explanation. Your comment was a big help!

**Comment by raineorshine** [comment] 2019-03-16 04:16
FYI: Regarding the original issue, if you find that `packageFile` is not needed as of ncu `v3.0.11`, then 4ee2ca4 did the trick.

**Comment by kylios** [comment] 2019-03-16 04:19
Hi @raineorshine , no problem, and glad I could help! Thanks for the fixes :)

**Comment by stoically** [comment] 2019-03-16 12:03
The issue described by OP and others is still present on Windows when ncu is executed in an environment based on MinTTY (such as Cygwin and Git Bash) or other TTY emulators which are not correctly detected by Node. `isTTY` is `false` and endlessly waits for `stdin`.

Since executing ncu with `winpty` in this case works as expected - a possible work-around would be wrapping the ncu bin into a shell script which checks for winpty and executes ncu with it if it's present. [`yarn` does that too](https://github.com/yarnpkg/yarn/blob/6dbedcc40052cee6143408062bec0a5104f4744c/bin/yarn#L17-L18).

**Comment by raineorshine** [comment] 2019-03-18 02:08
If anybody is able to implement a similar check for `winpty` like in yarn, that would be a huge help!

**Comment by kopax** [comment] 2019-03-22 18:38
I have hit this issue **on linux**, when I have tried to invoke `ncu` using `childProcess.spawn`. Using --packageFile` did the trick.

**Comment by angeldelacruzsdo** [comment] 2019-09-18 01:50
> Hey guys, this command worked out for me.
> Using gitbash MinTTY.
> Try running this command
> ncu -u --packageFile package.json
> ![npm-check-updates](https://user-images.githubusercontent.com/14350389/27818317-faa59b90-6049-11e7-8821-b00ec28707c6.png)

This Working

**Comment by KingDarBoja** [comment] 2019-12-26 00:02
Any progress on this issue? Just curious... The provided workaround does work on Win 10 with Git Bash.

**Comment by raineorshine** [comment] 2019-12-29 19:20
@KingDarBoja I don't believe anyone is actively working on this. Open to pull requests though.

**Comment by KingDarBoja** [comment] 2020-01-03 18:16
@raineorshine Managed to solve the problem based on @kylios comment as I noticed the if-else check at `findPackage` function didn't took into account the `pkgFileName` value as it was set to default on `getPackageFileName`.

Something like this:
```js
// ... More code
if (options.packageData) {
        pkgFile = null;
        pkgData = Promise.resolve(options.packageData);
    } else if (options.packageFile) {
        pkgFile = options.packageFile;
        pkgData = getPackageDataFromFile(pkgFile, pkgFileName);
    } else if (pkgFileName) {
        pkgFile = pkgFileName;
        pkgData = getPackageDataFromFile(pkgFile, pkgFileName);
    } else if (!process.stdin.isTTY) {
        // ... More code
    }
//... More code
```

Proof:
![image](https://user-images.githubusercontent.com/30560560/71740635-c19cbc00-2e2a-11ea-8300-9da4d92a3e32.png)

**Comment by raineorshine** [comment] 2020-01-03 23:59
`pkgFileName` is always truthy, thus the code proposed would never reach `if (!process.stdin.isTTY) { ... }`, breaking stdin functionality. We need a solution that correctly detects `isTTY` across platforms.

**Comment by stoically** [comment] 2020-01-04 00:03
Personally I think it might make sense to make reading from stdin opt-in, as breaking change. Since arguably reading from stdin is the much less used branch.

**Comment by raineorshine** [comment] 2020-01-04 00:05
That makes sense to me.

**Comment by KingDarBoja** [comment] 2020-01-04 16:33
@raineorshine I know but as most users have to provide the package filename by using the `--packageFile` option, it doesn't make sense to step into the `process.stdin.isTTY` part.

@stoically makes sense if someone wish to use it, as a new flag which should take priority over the existing checks and everyone would (I think) be happy about it.

**Comment by KingDarBoja** [comment] 2020-11-19 20:13
No idea what changed on this library or my git bash but I no longer need `--packageFile` to make it work 🚀

**Comment by raineorshine** [comment] 2020-11-19 20:32
@KingDarBoja Interesting. If an old version of `ncu` such as `v2` works for you now, then it's your shell. Otherwise I'd be curious what exact version of `ncu` it started working for you.

**Comment by KingDarBoja** [comment] 2020-11-19 20:35
> @KingDarBoja Interesting. If an old version of `ncu` such as `v2` works for you now, then it's your shell. Otherwise I'd be curious what exact version of `ncu` it started working for you.

I updated this week to `10.2.1` that's why I am surprised its working out of the box.

**Comment by raineorshine** [comment] 2020-11-19 20:41
Well that's good news at least. It's unclear whether it's node, npm, ncu, or one of ncu's dependencies that fixed it. If someone else can confirm I'll close the issue!

**Comment by hizablet** [comment] 2021-02-11 04:35
> I installed node v4.1.0 and ran `ncu` without a problem. All unit tests passing, too.
> 
> What happens when you run this command?
> 
> ```
> echo '{"dependencies":{"express": "1"}}' | ncu
> ```
> 
> Please provide any additional information you can about the problem.

hi，i meet with the problem:
my environment is：
```
NexT version 8.0.0
Documentation: https://theme-next.js.org
========================================
hexo: 5.3.0
hexo-cli: 4.2.0
os: Windows_NT 10.0.19041 win32 x64
node: 14.15.4
v8: 8.4.371.19-node.17
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1i
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
```
and i use the code `npm i -g npm-check-updates` to install the package
it succeed，and then i use the git bash in my blog root directory，use `ncu`  or `ncu -u`，it display this：
```
$ ncu -u
Hmmmmm... this is taking a long time. Your console is telling me to wait for input
on stdin, but maybe that is not what you want.
Try winpty ncu.cmd, or specify a package file explicitly with --packageFile package.json.
See https://github.com/raineorshine/npm-check-updates/issues/136#issuecomment-155721102
``` 
i see this issue，so which is the answer to this problem?

**Comment by raineorshine** [comment] 2021-02-11 13:38
@hizablet Specify `--packageFile package.json`.

**Comment by donocode** [comment] 2021-03-10 22:53
Just in case anyone ends up here while trying to run `ncu` through execa, you can make things work correctly with the stdin option:

```js
execa('ncu', { preferLocal: true, stdin: process.stdin })
```

For some reason it does not work without it and only when piping stdout are you able to get a warning message which links here.

**Comment by raineorshine** [comment] 2021-03-11 15:13
> trying to run `ncu` through execa

As an aside, you can [require npm-check-updates](https://github.com/raineorshine/npm-check-updates#moduleprogrammatic-usage) which may work better in some circumstances.

**Comment by tmarcinkowski-logitech** [comment] 2022-01-27 09:20
For anyone using `concurrently` and experiencing this issue as well - you either need to explicitly set `--packageFile` as said before, or pass `--raw` option to `concurrently` (but you lose prefixing in this case).

An example:
```sh
npx concurrently \
  -n root,common,ui,api \
  "npx npm-check-updates --packageFile package.json" \
  "npx npm-check-updates --packageFile package.json --prefix common" \
  "npx npm-check-updates --packageFile package.json --prefix ui" \
  "npx npm-check-updates --packageFile package.json --prefix api"
```

**Comment by wangjing199196ok** [comment] 2022-07-15 08:06
> > I installed node v4.1.0 and ran `ncu` without a problem. All unit tests passing, too.
> > What happens when you run this command?
> > ```
> > echo '{"dependencies":{"express": "1"}}' | ncu
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please provide any additional information you can about the problem.
> 
> hi，i meet with the problem: my environment is：
> 
> ```
> NexT version 8.0.0
> Documentation: https://theme-next.js.org
> ========================================
> hexo: 5.3.0
> hexo-cli: 4.2.0
> os: Windows_NT 10.0.19041 win32 x64
> node: 14.15.4
> v8: 8.4.371.19-node.17
> uv: 1.40.0
> zlib: 1.2.11
> brotli: 1.0.9
> ares: 1.16.1
> modules: 83
> nghttp2: 1.41.0
> napi: 7
> llhttp: 2.1.3
> openssl: 1.1.1i
> cldr: 37.0
> icu: 67.1
> tz: 2020a
> unicode: 13.0
> ```
> 
> and i use the code `npm i -g npm-check-updates` to install the package it succeed，and then i use the git bash in my blog root directory，use `ncu` or `ncu -u`，it display this：
> 
> ```
> $ ncu -u
> Hmmmmm... this is taking a long time. Your console is telling me to wait for input
> on stdin, but maybe that is not what you want.
> Try winpty ncu.cmd, or specify a package file explicitly with --packageFile package.json.
> See https://github.com/raineorshine/npm-check-updates/issues/136#issuecomment-155721102
> ```
> 
> i see this issue，so which is the answer to this problem?

Have you solved the problem yet? I have meet the same problem...

**Comment by raineorshine** [comment] 2022-11-15 12:10
Auto stdin removed in 7005bc6

**Closed by raineorshine** 2022-11-15 12:11 UTC
Labels: bug
