### ISSUE TITLE
Update patch version is not working

### ISSUE THREAD

**Issue by kvskranthikumar** [raineorshine/npm-check-updates#739] opened 2020-09-28 08:58 UTC
I have the latest version ncu v9.0.2
When running the below command it is not updating the packages -

**_npm-check-updates  --target patch -u_**

All dependencies match the patch package versions :)

Current package in the package.jon file -
"@by/catman-react-utils": "^20.1.6"

These are private repositories in jFrog Artifactory -
npm view @by/catman-react-utils versions

[
  '20.1.1',   '20.1.2',
  '20.1.3',   '20.1.4',
  '20.1.5',   '20.1.6',
  '20.1.7',   '20.1.8',
  '2020.1.0'
]

I am expecting 20.1.6 --> 20.1.8

**Comment by raineorshine** [comment] 2020-09-28 21:47
Thanks for reporting. We should be able to find the cause if you can output some additional information. You'll need to add some `console.log` statements to your installed npm-check-updates (found at `which npm-check-updates`).

1. Run `npm-check-updates --target patch --loglevel verbose`
1. Run `npm view @by/catman-react-utils time`
1. Add `console.log(versions)` inside the [patch function](https://github.com/raineorshine/npm-check-updates/blob/master/lib/package-managers/npm.js#L340).
1. Add `console.log(_.filter(versions, filterPredicate(options))` inside the same patch function.

**Comment by kvskranthikumar** [comment] 2020-09-29 13:23
@raineorshine, when you say to add some console.log in npm-check-updates, what do you mean by that? Do I need to open the build.js and add console.log, if yes what are the places I need to add them?

I have Windows OS and the package is installed globally at C:\Users\[UserName]\AppData\Roaming\npm\node_modules\npm-check-updates

**Comment by raineorshine** [comment] 2020-09-29 14:51
Duplicate of #737. Published in `v9.0.3`. Can you check if it's fixed?

**Comment by kvskranthikumar** [comment] 2020-09-30 19:28
Thank you.
It is working!

**Closed** 2020-09-30 19:50 UTC
Labels: bug, duplicate
